name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: molisawa
        DOCKER_PASSWORD: 3323550062Pp
      run: docker login -u molisawa -p 3323550062Pp
      
    - name: Build the Docker image
      run: docker build -t varsubham/cicd-pipeline .
    - name: Push to Dockerhub
      run: docker push varsubham/cicd-pipeline:latest
