name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        aws-region: us-east-1
    - name: Login to Amazon ECR private
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build, tag, and push docker image to Amazon ECR Public
      env:
        REGISTRY: public.ecr.aws
        REGISTRY_ALIAS: z7e2z2v1
        REPOSITORY: p-aws-ecr
        IMAGE_TAG: latest
      run: |
          sudo docker build -t 690464062239.dkr.ecr.us-east-1.amazonaws.com/p-aws-ecrp:$IMAGE_TAG .
          sudo docker push 690464062239.dkr.ecr.us-east-1.amazonaws.com/p-aws-ecrp:$IMAGE_TAG

    
